version: '3'

services:
  postgres_db:
    container_name: postgres_db
    hostname: postgres_db
    image: postgres
    volumes:
      - /var/jplsightm/dbdata:/var/lib/postgresql/data
    ports:
      - 5432:5432

